### ISSUE TITLE
DataExtractor -> couldnt open <filename>

### ISSUE THREAD

**Issue by Feuerdraht** [CypherCore/Tools#6]
Hi.
First: Thanks for your work! Really appreciated.

I have tried to use the dataextractor and i get an error.
Maps extractor is running fine. When then the vamps are started, 
it works for a while and then stops with the following msg: 

```
.  .  .
Extracting File003B4B5F.xxx
Extracting File002EB47E.xxx
Extracting File002C6D7C.xxx
Done!
Processing Map 0
Extracting FILE351391:8X.xxx......26%
No such file.
Couldn't open RootWmo!!!
WMOInstance.WMOInstance: couldn't open FILE351391:8X.xxx
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'FILE351391:8X.xxx' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DataExtractor.Vmap.ADTFile.init(UInt32 map_num, UInt32 originalMapId) in D:\cyphercore-tools\Source\DataExtractor\Vmap\Adt.cs:line 139
   at DataExtractor.Vmap.VmapFile.ParsMapFiles() in D:\cyphercore-tools\Source\DataExtractor\Vmap\VmapFile.cs:line 141
   at DataExtractor.Program.ExtractVMaps() in D:\cyphercore-tools\Source\DataExtractor\Program.cs:line 305
   at DataExtractor.Program.Main(String[] args) in D:\cyphercore-tools\Source\DataExtractor\Program.cs:line 105
```

I did a fresh compile (VS2019, Win10 20H2) and still:
mapextractor cant find a file it looks for...
I can run the extractors from Trinity Master against the used client error-free and it generates everything just fine.

Please excuse me, if this is not an issue and i am just too dumb to use the generator ;) 

Thanks in advance for your help.

**Comment by hondacrx** [comment]
Fixed in 9a17b7bbf800a4c71e2cf2ce3465c8eb418e6f84

**Comment by Feuerdraht** [comment]
Hey. Thanks a lot for the fast fix. 
Unfortuneately it now stops at another file...

```
Extracting File003B4B5F.xxx
Extracting File002EB47E.xxx
Extracting File002C6D7C.xxx
Done!
Processing Map 0
Extracting FILE8X.xxx.............26%
No such file.
Couldn't open RootWmo!!!
WMOInstance.WMOInstance: couldn't open FILE8X.xxx
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'FILE8X.xxx' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DataExtractor.Vmap.ADTFile.init(UInt32 map_num, UInt32 originalMapId) in D:\cyphercore-tools\Source\DataExtractor\Vmap\Adt.cs:line 139
   at DataExtractor.Vmap.VmapFile.ParsMapFiles() in D:\cyphercore-tools\Source\DataExtractor\Vmap\VmapFile.cs:line 141
   at DataExtractor.Program.ExtractVMaps() in D:\cyphercore-tools\Source\DataExtractor\Program.cs:line 314
   at DataExtractor.Program.Main(String[] args) in D:\cyphercore-tools\Source\DataExtractor\Program.cs:line 113
```

Am i doing something wrong? 
Thanks again for your help. Very apprecitated. 
Greetings

**Comment by hondacrx** [comment]
this needs alot of work still.

**Comment by MaxtorCoder** [comment]
> this needs alot of work still.

Big F

**Comment by ayell** [comment]
U think u will push a fix ? Or if not maybe I can help u if u tell me how can I help . I need a server in C# ^^

**Comment by MaxtorCoder** [comment]
> U think u will push a fix ? Or if not maybe I can help u if u tell me how can I help . I need a server in C# ^^

I'll see if I can make a PR today. I think Honda is a bit busy atm.

**Comment by hondacrx** [comment]
> U think u will push a fix ? Or if not maybe I can help u if u tell me how can I help . I need a server in C# ^^

you can use TC extractors till i can push a working fix.

**Comment by Axdrell** [comment]
Hi, I also would like to try using the extractors and seeing your work by running the private server. Will continue checking weekly to see if you pushed the extractor fix. 

Thanks

**Comment by Axdrell** [comment]
I tried using the TC extractors but the worldserver crashes - "Unable to load critical files" when it tries to read the vmaps directory.

**Comment by hondacrx** [comment]
make sure your using the newest TC extractors  and newest CypherCore, they should work  i will check to make sure

**Comment by hondacrx** [comment]
Should be fixed in https://github.com/CypherCore/Tools/commit/672e6ca76a65b3a7943f04fff63833b4233b4e40
