### ISSUE TITLE
Extractor stream.ReadInt32

### ISSUE THREAD

**Issue by fIyingPhoenix** [CypherCore/Tools#8]
'Unable to read beyond the end of the stream

**Comment by MaxtorCoder** [comment]
At least do effort to place the entire log instead of this.....

**Comment by flyingFalcon22** [comment]
sry, new to this. 

System.IO.EndOfStreamException
  HResult=0x80070026
  Message=Unable to read beyond the end of the stream.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at DataExtractor.CASCLib.WowRootHandler..ctor(BinaryReader stream) in C:\Users\Andrei Caran\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\RootHandlers\WowRootHandler.cs:line 161
   at DataExtractor.CASCLib.CASCHandler..ctor(CASCConfig config) in C:\Users\Andrei Caran\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\CASCHandler.cs:line 33
   at DataExtractor.CASCLib.CASCHandler.Open(CASCConfig config) in C:\Users\Andrei Caran\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\CASCHandler.cs:line 60
   at DataExtractor.CASCLib.CASCHandler.OpenStorage(CASCConfig config) in C:\Users\Andrei Caran\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\CASCHandler.cs:line 42
   at DataExtractor.Program.Main(String[] args) in C:\Users\Andrei Caran\Desktop\Tools-master\Source\DataExtractor\Program.cs:line 88

**Comment by fIyingPhoenix** [comment]
Sry, new to this. :)

System.IO.EndOfStreamException
  HResult=0x80070026
  Message=Unable to read beyond the end of the stream.
  Source=System.Private.CoreLib
  StackTrace:
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at DataExtractor.CASCLib.WowRootHandler..ctor(BinaryReader stream) in C:\Users\User\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\RootHandlers\WowRootHandler.cs:line 161
   at DataExtractor.CASCLib.CASCHandler..ctor(CASCConfig config) in C:\Users\User\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\CASCHandler.cs:line 33
   at DataExtractor.CASCLib.CASCHandler.Open(CASCConfig config) in C:\Users\User\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\CASCHandler.cs:line 60
   at DataExtractor.CASCLib.CASCHandler.OpenStorage(CASCConfig config) in C:\Users\User\Desktop\Tools-master\Source\DataExtractor\Framework\CASCLib\CASCHandler.cs:line 42
   at DataExtractor.Program.Main(String[] args) in C:\Users\User\Desktop\Tools-master\Source\DataExtractor\Program.cs:line 88

**Comment by MaxtorCoder** [comment]
What client version are you attempting

**Comment by fIyingPhoenix** [comment]
on the latest 9.1 client

**Comment by MaxtorCoder** [comment]
> on the latest 9.1 client

9.1 is not supported...

**Comment by hondacrx** [comment]
Fixed in https://github.com/CypherCore/Tools/commit/672e6ca76a65b3a7943f04fff63833b4233b4e40
